# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
apt_packages:
    - libv8-dev

addons:
  apt:
    update: true
    packages: libgit2-dev
    sources:
      - sourceline: 'ppa:cran/libgit2'

after_success:
  - Rscript -e 'covr::codecov()'

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: oldrel

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
